### ISSUE TITLE
开始时间设为new Date()

### ISSUE THREAD

**Issue by Theoneee** [JustinRoom/JSCKit#3]
月份仍然可以选择到以前的月份。年和日正常。

**Comment by JustinRoom** [comment]
麻烦贴下你的调用代码。谢谢！

**Comment by Theoneee** [comment]
`   
datePickerUtil.initTimePicker(_mActivity,new Date(),datePickerUtil.getNextMonthDate());

 public void initTimePicker(Context context, Date start, Date end) {
        this.context = context;
        this.start = start;
        this.end = end;
        //方式一：构建自己的builder
        TBuilder = new DateTimePicker.Builder(context)
                .setOk("确定")
                .setCancel("取消")
                .setCancelTextColor(Color.RED)
                .setOkTextColor(context.getResources().getColor(R.color.status_color))
                .setTitleTextColor(0xFF999999)
                .setSelectedTextColor(context.getResources().getColor(R.color.colorAccent))
                .setShowType(DateTimePicker.ShowType.DAY);
    }

public void show(String title, DateTimePicker.ResultHandler resultHandler) {
        TBuilder.setTitle(title);
        new DateTimePicker(context, resultHandler, start, end, TBuilder).show(new Date());
    }


`

主要的也就是最后那个方法的代码。开始时间设置的是new Date()。 DateTimePicker 里我也打了日志，monthPicker设置的months也确实是从这个月之后的，但是显示上的却依然有以前的 
months = [10, 11, 12]。
![s81031-134912](https://user-images.githubusercontent.com/32156330/47768622-d0ae4880-dd13-11e8-849d-71a548c4c4e2.jpg)

**Comment by Theoneee** [comment]
`    public Date getNextMonthDate() {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        calendar.add(Calendar.MONTH,1);
        return calendar.getTime();
    }`

结束时间设置的是一个月之后。今天31号，月份加一个月应该是11月31号，但是没有31，所以应该是12月1日。日志打印出来应该显示的是没问题的。

**Comment by Theoneee** [comment]
建议：当结束时间小于或等于今天时，setOnSelectListener里不应该改变高等级时低等级联动变化。只当结束时间大于或等于今天时（此时有时间限制）,更改时才改变下一等级。

**Comment by Theoneee** [comment]
endCalendar.getTime().getTime() >= new Date().getTime();

**Comment by Theoneee** [comment]
上一级改变之后都要重新判断是否可以滚动。

**Comment by Theoneee** [comment]
当开始日期的年份和结束日期的年份都是一样时，月份就会显示全部。

**Comment by Theoneee** [comment]
//months
        if (curShowType.value >= ShowType.MONTH.value) {
            months.clear();
            //the same year
            if (startYear == endYear) {
                for (int i = startMonth; i <= endMonth; i++) {
                    months.add(formatTimeUnit(i));
                }
            }

你写成了1

**Comment by JustinRoom** [comment]
好的。下个版本我会修复这个问题。非常感谢你的使用！可以加我WX相互探讨、相互学习：eoy9527。

**Comment by JustinRoom** [comment]
版本0.4.8已经修复这个问题。非常感谢！

**Comment by Theoneee** [comment]
我加了你QQ，你没同意。

**Comment by JustinRoom** [comment]
手机上连QQ都没有了，加WX: eoy9527
